[package]
name = "multi_thread"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
rand = "0.9.0-alpha.1"
thread_local = "1.1"
tokio = { version = "1.40.0", features = ["full"] }
